# Generated by Django 3.1 on 2020-09-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweetmaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
