# Generated by Django 3.1 on 2020-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200907_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_flag',
            field=models.BooleanField(default=False),
        ),
    ]
